Communication_Board/Communication_Board/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from expirations import views as exp

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('expirations.urls')),
]

Communication_Board/expirations/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views as exp_view

urlpatterns = [
    # url(r'^$', exp_view.home, name = 'home'),
    url(r'^$', exp_view.DrugListView.as_view() , name = 'drug_list'),
    url(r'^list/$', exp_view.DrugExpListView.as_view() , name = 'drug_exp_list'),
    url(r'^drug/new/$',exp_view.CreateDrugView.as_view(), name = 'drug_new'),
    url(r'^drug/(?P<pk>\d+)$', exp_view.DrugDetailView.as_view(), name = 'drug_detail'),
    url(r'^drug/(?P<pk>\d+)/delete$', exp_view.DrugDeleteView.as_view(), name = 'drug_delete'),
    url(r'^drug/(?P<pk>\d+)/expiration$', exp_view.CreateExpirationView.as_view(), name = 'add_expiration'),
    url(r'^drug/(?P<pk>\d+)/expiration/delete$', exp_view.ExpirationDeleteView.as_view(), name = 'expiration_delete'),
    url(r'^drug/(?P<pk>\d+)/barcode/new/$', exp_view.CreateBarcodeView.as_view(), name = 'add_barcode'),

]

Communication_Board/expirations/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
import datetime
from django.db import models
from django.db.models import Min

# Create your models here.

class Drug(models.Model):
    #drug_barcode = models.ForeignKey('expirations.Barcode', related_nam='barcodes')
    name = models.CharField(max_length= 200)

    # def get_absolute_url(self):
    #     return reverse('drug_list')

    def __unicode__(self):
        return self.name

    def early_exp(self):
        return self.expiration_dates.all().aggregate(Min('expirationDate')).values()[0]


class Expiration(models.Model):

    facility_Choices = (
        ('RWC', 'Redwood City Inpatient'),
        ('SC', 'Santa Clara Inpatient'),
        ('SLN', 'San Leandro Inpatient'),
    )

    facility = models.CharField(max_length = 100, choices = facility_Choices, default = 'RWC')

    drug_Linked = models.ForeignKey('expirations.Drug', related_name = 'expiration_dates')

    qty = models.IntegerField(default = 1)
    date_entered = models.DateField(auto_now=True)
    expirationDate = models.DateField(default = datetime.date.today)
    comments = models.TextField(null = True)

    def __unicode__(self):
        return str(self.expirationDate)

    def quantity(self):
        return int(self.quantity)

    def return_facility(self):
        return str(self.facility)

class Barcode(models.Model):
    drug = models.ForeignKey('expirations.Drug', related_name = 'barcode_for_drug')
    barCode = models.CharField(max_length= 40)

    def __unicode__(self):
        return str(self.barCode)

Communication_Board/expirations/forms.py
from django import forms
from .models import Drug, Expiration, Barcode

class DrugForm(forms.ModelForm):

    class Meta:
        model = Drug
        fields = ('name',)


class ExpirationForm(forms.ModelForm):
    facility = forms.ChoiceField(choices = Expiration.facility_Choices)
    class Meta:
        model = Expiration
        fields = ('qty', 'facility','expirationDate',)


class BarcodeForm(forms.ModelForm):
    class Meta:
        model = Barcode
        fields = ('barCode',)

Communication_Board/expirations/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from django.template import Context

from django.http import JsonResponse

from .models import Drug, Expiration, Barcode
from .forms import DrugForm, ExpirationForm, BarcodeForm

from django.urls import reverse_lazy, reverse

from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)

# Create your views here.

class DrugListView(ListView):
    context_object_name = 'drugs'
    model = Drug
    template_name = 'expirations/drug_list.html'

    def get_queryset(self):
        return Drug.objects.all().order_by('name')

class DrugExpListView(ListView):
    context_object_name = 'drugs_exp'
    model = Drug
    template_name = 'expirations/drug_list_byEXP.html'

    def get_queryset(self):
        return Expiration.objects.all().order_by('expirationDate')

class AjaxableResponseMixin(object):
    def form_valid(self, form):
        response = super(AjaxableResponseMixin, self).form_valid(form)
        if self.request.is_ajax():
            data = {
            'message': "Successfully added data"
            }
            return JsonResponse(data)
        else:
            return response

    def form_invalid(self, form):
        response = super(AjaxableResponseMixin, self).form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

class CreateDrugView(AjaxableResponseMixin, CreateView):
    redirect_field_name = reverse_lazy('drug_list')
    form_class = DrugForm

    model = Drug

    def form_invalid(self, form):
        response = super(CreateDrugView, self).form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status = 400)
        else:
            return response

    def form_valid(self, form):
        response = super(CreateDrugView, self).form_valid(form)
        if self.request.is_ajax():
            print(form.cleaned_data)
            data = {"message": "Success"}
            return JsonResponse(data)
        else:
            return response

    def get_success_url(self):
        return reverse_lazy('drug_new')

class DrugDetailView(DetailView):
    template_name = 'expirations/drug_detail.html'
    model = Drug

    def get_context_data(self, **kwargs):
        drug_Pk = self.kwargs['pk']
        context = super(DrugDetailView, self).get_context_data(**kwargs)
        context['exp'] = Drug.objects.get(pk = drug_Pk).expiration_dates.all().order_by('expirationDate')
        return context

class DrugDeleteView(DeleteView):
    model = Drug
    success_url = reverse_lazy('drug_list')

class CreateExpirationView(AjaxableResponseMixin, CreateView):
    model = Expiration
    template_name = 'expirations/add_exp.html'
    form_class = ExpirationForm

    def form_valid(self, form):
        #response = super(CreateExpirationView, self).form_valid(form)
        pk = self.kwargs['pk']
        exp = Expiration()
        exp.expirationDate = form.cleaned_data['expirationDate']
        exp.qty = form.cleaned_data['qty']
        exp.facility = form.cleaned_data['facility']
        #exp.comments = self.request.POST['comments']
        exp.drug_Linked = Drug.objects.get(pk = pk)
        exp.save()
        data = {"message": "Success"}
        return JsonResponse(data)

    def form_invalid(self, form):
        response = super(CreateExpirationView, self).form_invalid(form)
        if form.is_ajax():
            return JsonResponse(form.errors, status = 400)
        else:
            return response

    def get_context_data(self):
        drug_pk = self.kwargs['pk']
        context = {"drug_name" : Drug.objects.get(pk = drug_pk), 'form':self.get_form()}
        return context

    def get_success_url(self):
        return reverse_lazy('drug_detail')

class ExpirationDeleteView(DeleteView):
    model = Expiration
    success_url = reverse_lazy('drug_list')
##funcs only


class CreateBarcodeView(CreateView):
    model = Barcode
    template_name = 'expirations/add_barcode.html'
    form_class = BarcodeForm

    def form_valid(self, form):
        self.object = form.save(commit = False)
        barcode = Barcode()
        barcode.barCode = form.cleaned_data['barCode']
        barcode.drug = Drug.objects.get(pk = self.kwargs ['pk'])
        barcode.save()
        return redirect('drug_detail', pk = self.kwargs['pk'])

    def get_context_data(self):
        drug_pk = self.kwargs['pk']
        context = {"drug_name": Drug.objects.get(pk = drug_pk), 'form':self.get_form()}
        return context


def home(request):
    return render(request, 'expirations/index.html')

Communication_Board/expirations/templates/expirations/add_barcode.html
{% extends 'expirations/index.html' %}
{% block content %}
<div class = "container">
    <h1>Add barcode for:</h1>
    <h4>{{drug_name.name}}</h4>
    <form method="POST" class="post-form">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

Communication_Board/expirations/templates/expirations/add_exp.html
{% extends 'expirations/index.html' %}

{% block content %}
<h1>Add Expiration for:</h1>
<h4>{{drug_name.name}}</h4>
<form id = "add_exp_id" method="POST" class="post-form">
{% csrf_token %}
{{form.as_p}}
<button id = "submit_exp" type="submit" class="btn btn-primary">Save</button>
</form>
<p>
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-success">
      <div class="panel-heading">Successfully Added</div>
      <div class="panel-body" id = "success">
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block javascript %}
<script>
  $('#id_expirationDate').datepicker({
        changeMonth: true,
        changeYear: true,
        startView: 2,
        autoclose: true,
        maxDate: "+5y",
        minDate: "-1y",
  });

$(document).ready(function(){
  var frm = $("#add_exp_id")
    frm.submit(function(e){
      e.preventDefault();
      $.ajax({
        type: "POST",
        url: "{% url 'add_expiration' pk=drug_name.id %}",
        data: frm.serialize(),
        success: function(data){
            $('#success').append( $("#id_expirationDate").val() + " has been added to {{ drug_name.name }}<br>");
            $('#id_qty').val("1");
        }
      })
    });
})
</script>
{% endblock %}

Communication_Board/expirations/templates/expirations/drug_confirm_delete.html
{% extends "expirations/index.html" %}
{% block content %}
<div class='container'>
  <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete: <h2><span class="label label-warning">{{ object }}</span></h2></p><br><br>
    <input class='btn btn-danger' type="submit" value="Confirm" />
  </form>
</div>
{% endblock %}

Communication_Board/expirations/templates/expirations/drug_detail.html
{% extends 'expirations/index.html' %}

{% block content %}
      <h1>{{ drug.name }}</h1>
      <a class="btn btn-primary" href="{% url 'drug_delete' pk=drug.pk %}"><span class ="glyphicon glyphicon-remove" style="font-size: 15px"></span> DELETE Drug</a>
      <a class="btn btn-info" href="{% url 'add_barcode' pk=drug.pk %}"><span class ="glyphicon glyphicon-barcode" style="font-size: 15px"></span> Add A Barcode</a>
      <h2>Expirations</h2>
      <a class = "btn btn-success" href="{% url 'add_expiration' pk=drug.pk %}"><span class ="glyphicon glyphicon-calendar" style="font-size: 15px"></span> Add An Expiration</a>
      <p>
      <div class="container-fluid-left">
        <div class="row">
          <div class="col-md-4">
            <div class="panel panel-success">
              <div class = 'panel-heading'>
                <h4>RWC</h4>
             </div>
             <div class="panel-footer">
               {% for x in exp %}
               {% if x.facility == 'RWC'%}
                    {{x.qty}} unit(s) expiring {{x.expirationDate}} <a href = "{% url 'expiration_delete' pk=x.pk %}"><span class = "glyphicon glyphicon-remove"></span></a><br>
               {% endif %}
               {% endfor %}
             </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="panel panel-primary">
              <div class = 'panel-heading'>
               <h4>SC</h4>
             </div>
             <div class="panel-footer">
               {% for x in exp %}
               {% if x.facility == 'SC'%}
                    {{x.qty}} unit(s) expiring {{x.expirationDate}} <a href = "{% url 'expiration_delete' pk=x.pk %}"><span class = "glyphicon glyphicon-remove" ></span></a><br>
               {% endif %}
               {% endfor %}
             </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="panel panel-info">
              <div class = 'panel-heading'>
               <h4>SLN</h4>
             </div>
             <div class="panel-footer">
               {% for x in exp %}
               {% if x.facility == 'SLN'%}
                    {{x.qty}} unit(s) expiring {{x.expirationDate}} <a href = "{% url 'expiration_delete' pk=x.pk %}"><span class = "glyphicon glyphicon-remove"></span></a><br>
               {% endif %}
               {% endfor %}
             </div>
            </div>
          </div>
        </div>
      </div>


{% endblock %}

Communication_Board/expirations/templates/expirations/drug_form.html
{% extends 'expirations/index.html' %}

{% block content %}
<div class = "container">
    <h1>Add A Drug</h1>

    <form id="drug_form_id" method="POST" class="post-form">
    {% csrf_token %}
    {{form.as_p}}
    <button id = "submit_drug" type="submit" class="btn btn-primary">Save</button>
    </form>
    <br>
    <div class="row">
      <div class="col-md-4">
        <div class="panel panel-success">
          <div class="panel-heading">Successfully Added</div>
          <div class="panel-body" id = "success">
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}
{% block javascript %}
<script>
$(document).ready(function(){
  var frm = $("#drug_form_id")
    frm.submit(function(e) {
      e.preventDefault();
      $.ajax({
        type:"POST",
        url: "{% url 'drug_new' %}",
        data: $(this).serialize(),
        success: function(data){
          console.log(data.message)
          $('#success').append( $("#id_name").val() + " has been added to the Drug List<br>");
          $("#drug_form_id").closest('form').find("input[type=text]").val("");
        }
      })
    });
})
</script>
{% endblock %}

Communication_Board/expirations/templates/expirations/drug_list.html
{% extends 'expirations/index.html' %}

{% block content %}
    {% for drug in drugs %}
    <div class = '.col-sm-12'>
        <ul class = 'list-group'>
            <li class = "list-group-item" >
              <span class = "badge">First Expiration: {{ drug.early_exp|date:"l M d Y" }}</span>
              <a href="{% url 'drug_detail' pk=drug.pk %}">{{ drug.name }}</a>
              {% regroup drug.expiration_dates.all by facility as facility_list %}
              {% for x in facility_list %}
              <span class="label label-info">{{ x.grouper }}</span>
              {% endfor %}
            </li>
        </ul>
    </div>
    {% endfor %}
{% endblock %}

Communication_Board/expirations/templates/expirations/drug_list_byEXP.html
{% extends 'expirations/index.html' %}

{% block content %}
<div class="container-fluid">
    {% for drug in drugs_exp %}
    <div class = '.col-sm-12'>
        <ul class = 'list-group'>
            <li class = "list-group-item" >
              <span class = "badge">First Expiration: {{ drug.expirationDate|date:"l M d Y" }}</span>
              <a href="{% url 'drug_detail' pk=drug.drug_Linked.pk %}">{{ drug.drug_Linked.name }}</a>
              <span class="label label-info">{{ drug.facility }}</span>
            </li>
        </ul>
    </div>
    {% endfor %}
</div>
{% endblock %}

Communication_Board/expirations/templates/expirations/expiration_confirm_delete.html
{% extends "expirations/index.html" %}
{% block content %}
<div class='container'>
  <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete: <h2><span class="label label-warning">{{ object }}</span></h2></p><br><br>
    <input class='btn btn-danger' type="submit" value="Confirm" />
  </form>
</div>
{% endblock %}

Communication_Board/expirations/templates/expirations/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Expirations Tracker</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        {# Fonts#}
        <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">
        <!---DatePicker-->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            body {
                padding-top: 70px;
            }
            @media (max-width: 980px) {
                body {
                    padding-top: 70px;
                }
            }
        </style>
    </head>

<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navBar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand">Expirations</a>
      </div>
      <div class="collapse navbar-collapse" id="navBar">
       <ul class="nav navbar-nav">
         <li class="nav-item"><a href="{% url 'drug_list' %}"><span class ="glyphicon glyphicon-home"></span> Home</a></li>
         <li class="nav-item"><a href="{% url 'drug_new' %}"><span class = "glyphicon glyphicon-plus"></span> Add Drugs</a></li>
         <li class="nav-item"><a href="{% url 'drug_exp_list'%}"><span class = "glyphicon glyphicon-calendar"></span> List By Expirations</a></li>
         <li class="nav-item"><a href="#"><span class = "glyphicon glyphicon-map-marker"></span> Facilities Serviced</a></li>
       </ul>
    </div>
  </div>
  </nav>
    <div class='container-fluid'>
    {% block content %}
    {% endblock %}
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
        <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="Stylesheet" type="text/css" />
    {% block javascript %} {% endblock %}
</body>
</html>